# Generated by Django 5.2.1 on 2025-05-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream_url', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_type', models.CharField(choices=[('barrier', 'На шлагбаум'), ('overview', 'Обзорная')], max_length=20)),
                ('barrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='parking.barrier')),
                ('id_parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='parking.parking')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_cameras', to='parking.parking')),
            ],
        ),
    ]
