# Generated by Django 5.2.1 on 2025-05-30 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Организация')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('blocked', 'Заблокирован'), ('pending', 'Ожидает проверки'), ('temporary', 'Временный доступ')], default='pending', max_length=20, verbose_name='Статус')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Неверный формат телефона', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/', verbose_name='Фото')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('access_from', models.DateTimeField(blank=True, null=True, verbose_name='Доступ с')),
                ('access_to', models.DateTimeField(blank=True, null=True, verbose_name='Доступ до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cars', models.ManyToManyField(blank=True, related_name='visitors', to='cars.car', verbose_name='Автомобили')),
                ('parking_access', models.ManyToManyField(blank=True, related_name='visitors', to='parking.parking', verbose_name='Доступ к парковкам')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
                'ordering': ['-created_at'],
            },
        ),
    ]
