# Generated by Django 5.2.1 on 2025-05-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('parking', '0001_initial'),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Время въезда')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Время выезда')),
                ('entry_photo', models.ImageField(blank=True, null=True, upload_to='visit_photos/entry/', verbose_name='Фото при въезде')),
                ('exit_photo', models.ImageField(blank=True, null=True, upload_to='visit_photos/exit/', verbose_name='Фото при выезде')),
                ('license_plate_detected', models.CharField(blank=True, max_length=20, null=True, verbose_name='Распознанный номер')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='cars.car', verbose_name='Автомобиль')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='parking.parking', verbose_name='Парковка')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitor.visitor', verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Журнал посещений',
                'verbose_name_plural': 'Журнал посещений',
                'ordering': ['-entry_time'],
            },
        ),
    ]
